// GENERATED by scripts/gen-constants.mjs — do not hand-edit.
// Source: vendor/espeak-ng (pinned commit) speak_lib.h + translate.h,
// cross-checked against piper1-gpl's src/piper/espeakbridge.c.

// -- espeak_Char_Type (text encoding passed to *TextToPhonemes*) --
export declare const espeakCHARS_AUTO: 0;
export declare const espeakCHARS_UTF8: 1;
export declare const espeakCHARS_8BIT: 2;
export declare const espeakCHARS_WCHAR: 3;
export declare const espeakCHARS_16BIT: 4;

// -- espeak_PHONEME_MODE bits --
export declare const espeakPHONEMES_SHOW: 0x01;
export declare const espeakPHONEMES_IPA: 0x02;
export declare const espeakPHONEMES_TRACE: 0x08;
export declare const espeakPHONEMES_MBROLA: 0x10;
export declare const espeakPHONEMES_TIE: 0x80;

// -- espeak_Initialize() option bits --
export declare const espeakINITIALIZE_PHONEME_EVENTS: 0x0001;
export declare const espeakINITIALIZE_PHONEME_IPA: 0x0002;
export declare const espeakINITIALIZE_DONT_EXIT: 0x8000;

// -- espeak_AUDIO_OUTPUT enum (from speak_lib.h, not a #define) --
export declare const AUDIO_OUTPUT_PLAYBACK: 0;
export declare const AUDIO_OUTPUT_RETRIEVAL: 1;
export declare const AUDIO_OUTPUT_SYNCHRONOUS: 2;
export declare const AUDIO_OUTPUT_SYNCH_PLAYBACK: 3;

// -- CLAUSE_* (internal to espeak-ng, not part of the public API — see
//    src/libespeak-ng/translate.h. Reproduced to match espeakbridge.c.) --
export declare const CLAUSE_INTONATION_FULL_STOP: 0x00000000;
export declare const CLAUSE_INTONATION_COMMA: 0x00001000;
export declare const CLAUSE_INTONATION_QUESTION: 0x00002000;
export declare const CLAUSE_INTONATION_EXCLAMATION: 0x00003000;
export declare const CLAUSE_TYPE_CLAUSE: 0x00040000;
export declare const CLAUSE_TYPE_SENTENCE: 0x00080000;
export declare const CLAUSE_PERIOD: 0x00080028;
export declare const CLAUSE_COMMA: 0x00041014;
export declare const CLAUSE_QUESTION: 0x00082028;
export declare const CLAUSE_EXCLAMATION: 0x0008302d;
export declare const CLAUSE_COLON: 0x0004001e;
export declare const CLAUSE_SEMICOLON: 0x0004101e;

export declare const CLAUSE_TERMINATOR_MASK: 0x000fffff;

/**
 * @param terminator raw terminator value from
 *   espeak_TextToPhonemesWithTerminator
 */
export declare function decodeTerminator(terminator: number): {
  terminator: string;
  isSentenceEnd: boolean;
};
